table tblTime
	lineageTag: 038704df-faff-4167-a9f1-c8e672e26dd4

	column Minute
		dataType: string
		lineageTag: 7c9902e8-4794-4a19-a00e-c24626a1bcc4
		summarizeBy: none
		sourceColumn: Minute

		annotation SummarizationSetBy = Automatic

	column TimeToMinute
		dataType: double
		lineageTag: 4ad4c4a1-6e36-4d72-a2ed-bfbcc137b93a
		summarizeBy: none
		sourceColumn: TimeToMinute

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Bucket-5min
		dataType: int64
		formatString: 0
		lineageTag: 64f553d2-daaa-437a-9f3e-cf691b8edd11
		summarizeBy: none
		sourceColumn: Bucket-5min

		annotation SummarizationSetBy = Automatic

	column Slot-5min
		dataType: dateTime
		formatString: Long Time
		lineageTag: d048db16-8879-42ad-85bb-7ab143e689b8
		summarizeBy: none
		sourceColumn: Slot-5min

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Bucket-10min
		dataType: int64
		formatString: 0
		lineageTag: 250db10f-8a86-471b-8962-c235715db75d
		summarizeBy: none
		sourceColumn: Bucket-10min

		annotation SummarizationSetBy = Automatic

	column Slot-10min
		dataType: dateTime
		formatString: Long Time
		lineageTag: 594933ee-c6d1-4f51-8e7f-a0991a6ffad0
		summarizeBy: none
		sourceColumn: Slot-10min

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Bucket-1hr
		dataType: int64
		formatString: 0
		lineageTag: 96c38cb9-52cd-410f-bc32-15f6e0ce5920
		summarizeBy: none
		sourceColumn: Bucket-1hr

		annotation SummarizationSetBy = Automatic

	column Slot-1hr
		dataType: dateTime
		formatString: Long Time
		lineageTag: 8a02cdd7-82e0-4d8d-91be-7f3f7d546407
		summarizeBy: none
		sourceColumn: Slot-1hr

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Bucket-3hr
		dataType: int64
		formatString: 0
		lineageTag: c37ef028-2031-422b-b403-c8ff00d62c66
		summarizeBy: none
		sourceColumn: Bucket-3hr

		annotation SummarizationSetBy = Automatic

	column Slot-3hr
		dataType: dateTime
		formatString: Long Time
		lineageTag: 341fd645-ef61-4d4e-890e-9ca2f532bab0
		summarizeBy: none
		sourceColumn: Slot-3hr

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Bucket-6hr
		dataType: int64
		formatString: 0
		lineageTag: 101c9658-50f3-4159-8787-43e63256805d
		summarizeBy: none
		sourceColumn: Bucket-6hr

		annotation SummarizationSetBy = Automatic

	column Slot-6hr
		dataType: dateTime
		formatString: Long Time
		lineageTag: b27c6c4a-1ae7-4b30-9da9-a7c8027f431e
		summarizeBy: none
		sourceColumn: Slot-6hr

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Bucket-12hr
		dataType: int64
		formatString: 0
		lineageTag: 99f16cee-3a58-481e-9c2b-9b4812c3a3bc
		summarizeBy: none
		sourceColumn: Bucket-12hr

		annotation SummarizationSetBy = Automatic

	column Slot-12hr
		dataType: dateTime
		formatString: Long Time
		lineageTag: 9fc71bd9-8f3a-44a6-91c6-265ab580d59d
		summarizeBy: none
		sourceColumn: Slot-12hr

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column PartOfDay
		dataType: string
		lineageTag: af664ec3-0f45-4981-a405-8ccb32bfbb74
		summarizeBy: none
		sourceColumn: PartOfDay
		sortByColumn: PartofDaySortOrder

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column PartofDaySortOrder
		dataType: string
		lineageTag: 0c7ed5bf-24d6-4192-bf6e-dece1cc259c1
		summarizeBy: none
		sourceColumn: PartofDaySortOrder

		annotation SummarizationSetBy = Automatic

	partition tblTime = m
		mode: import
		source = ```
				let
				    Source = {0..1439},
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Minute"}}),
				    #"Inserted Division" = Table.AddColumn(#"Renamed Columns", "Division", each [Minute] / 1440, type number),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Division",{{"Division", "TimeToMinute"}}),
				
				    #"Create-Bucket-5min" = Table.AddColumn(#"Renamed Columns1", "Bucket-5min", each Number.IntegerDivide([Minute], 5), Int64.Type),
				    #"Create-Slot-5min" = Table.AddColumn(#"Create-Bucket-5min", "Slot-5min", each [#"Bucket-5min"] * 5 / 1440),
				    #"Changed Type 5min" = Table.TransformColumnTypes(#"Create-Slot-5min",{{"Slot-5min", type time}}),
				
				    #"Create-Bucket-10min" = Table.AddColumn(#"Changed Type 5min", "Bucket-10min", each Number.IntegerDivide([Minute], 10), Int64.Type),
				    #"Create-Slot-10min" = Table.AddColumn(#"Create-Bucket-10min", "Slot-10min", each [#"Bucket-10min"] * 10/1440),
				    #"Changed Type 10min" = Table.TransformColumnTypes(#"Create-Slot-10min",{{"Slot-10min", type time}}),
				
				    #"Create-Bucket-1hr" = Table.AddColumn(#"Changed Type 10min", "Bucket-1hr", each Number.IntegerDivide([Minute], 60), Int64.Type),
				    #"Create-Slot-1hr" = Table.AddColumn(#"Create-Bucket-1hr", "Slot-1hr", each [#"Bucket-1hr"] * 60/1440),
				    #"Changed Type 1hr" = Table.TransformColumnTypes(#"Create-Slot-1hr",{{"Slot-1hr", type time}}),
				
				    #"Create-Bucket-3hr" = Table.AddColumn(#"Changed Type 1hr", "Bucket-3hr", each Number.IntegerDivide([Minute], 180), Int64.Type),
				    #"Create-Slot-3hr" = Table.AddColumn(#"Create-Bucket-3hr", "Slot-3hr", each [#"Bucket-3hr"] * 180/1440),
				    #"Changed Type 3hr" = Table.TransformColumnTypes(#"Create-Slot-3hr",{{"Slot-3hr", type time}}),
				
				    #"Create-Bucket-6hr" = Table.AddColumn(#"Changed Type 3hr", "Bucket-6hr", each Number.IntegerDivide([Minute], 360), Int64.Type),
				    #"Create-Slot-6hr" = Table.AddColumn(#"Create-Bucket-6hr", "Slot-6hr", each [#"Bucket-6hr"] * 360/1440),
				    #"Changed Type 6hr" = Table.TransformColumnTypes(#"Create-Slot-6hr",{{"Slot-6hr", type time}}),
				
				    #"Create-Bucket-12hr" = Table.AddColumn(#"Changed Type 6hr", "Bucket-12hr", each Number.IntegerDivide([Minute], 720), Int64.Type),
				    #"Create-Slot-12hr" = Table.AddColumn(#"Create-Bucket-12hr", "Slot-12hr", each [#"Bucket-12hr"] * 720/1440),
				    #"Changed Type 12hr" = Table.TransformColumnTypes(#"Create-Slot-12hr",{{"Slot-12hr", type time}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type 12hr", "PartOfDay", 
				  each if [#"Bucket-1hr"] >= 0 and [#"Bucket-1hr"] < 1 then "Late Evening (2200-0100)"  
				  else if [#"Bucket-1hr"] >= 1 and [#"Bucket-1hr"] < 5 then "Stupid Early (0000-0500)"
				  else if [#"Bucket-1hr"] >= 5 and [#"Bucket-1hr"] < 8 then "Early (0500-0800)"
				  else if [#"Bucket-1hr"] >= 8 and [#"Bucket-1hr"] < 12 then "Morning (0800-1200)"
				  else if [#"Bucket-1hr"] >= 12 and [#"Bucket-1hr"] < 17 then "Afternoon (1200-1700)"
				  else if [#"Bucket-1hr"] >= 17 and [#"Bucket-1hr"] < 22 then "Evening (1700-2200)"  
				  else if [#"Bucket-1hr"] >= 22 and [#"Bucket-1hr"] < 24 then "Late Evening (2200-0100)"  
				  else null),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "PartofDaySortOrder", 
				  each if [#"PartOfDay"] = "Early (0500-0800)" then 1
				  else if [#"PartOfDay"] = "Morning (0800-1200)" then 2
				  else if [#"PartOfDay"] = "Afternoon (1200-1700)" then 3
				  else if [#"PartOfDay"] = "Evening (1700-2200)" then 4
				  else if [#"PartOfDay"] = "Late Evening (2200-0100)" then 5 
				  else if [#"PartOfDay"] = "Stupid Early (0000-0500)" then 6
				  else null)
				  
				in
				    #"Added Custom1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

